[package]
name = "stuwe-telegram-rs"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = "*"
rusqlite = { version = "0.29.0", features = ["bundled"] }
chrono = "0.4.26"
regex = { version = "1.9.1", default-features = false }
lazy_static = "1.4.0"
uuid = "1.4.0"
hashmap = "0.0.1"
openssl = { version = "*", features = ["vendored"] }
thiserror = "1.0.43"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
reqwest = "0.11.18"
scraper = "0.17.1"
selectors = "0.25.0"
rand = "0.8.5"
cfg-if = "1.0.0"

[features]
# default = ["mensimates"]
mensimates = []

[profile.release]
strip = true
codegen-units = 1
lto = true
opt-level = "z"
