[package]
name = "stuwe-telegram-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = "*"
rusqlite = "0.29.0"
chrono = "0.4.26"
regex = { version = "1.8.4", default-features = false, features = ["std"] }
lazy_static = "1.4.0"
uuid = "1.4.0"
hashmap = "0.0.1"
thiserror = "1.0.43"
