[package]
name = "stuwe-telegram-rs"
version = "1.3.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "stuwe-telegram-rs"
path = "src/bin/stuwe-telegram-bin.rs"

[[bin]]
name = "mm-telegram-rs"
path = "src/bin/mm-telegram-bin.rs"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.4.6", features = ["derive", "wrap_help"] }
log = "0.4"
pretty_env_logger = "0.5"
rand = "0.8.5"
regex-lite = "0.1.0"
reqwest = { version = "0.11.18", features = ["cookies"] }
rusqlite = { version = "0.29.0" }
scraper = "0.17.1"
selectors = "0.25.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
static_init = "1.0.3"
teloxide = { version = "0.12", features = ["macros"] }
teloxide-core = "0.9.1"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = "*"
uuid = "1.4.0"

[features]
campusdual = []
default = ["campusdual"]

[profile.release]
strip = true
codegen-units = 1
lto = true
