[package]
name = "stuwe-telegram-rs"
version = "1.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "*", features = ["vendored"] }
cfg-if = "1.0.0"
chrono = "0.4.26"
log = "0.4"
pretty_env_logger = "0.5"
rand = "0.8.5"
regex-lite = "0.1.0"
reqwest = "0.11.18"
rusqlite = { version = "0.29.0", features = ["bundled"] }
scraper = "0.17.1"
selectors = "0.25.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
static_init = "1.0.3"
teloxide = { version = "0.12", features = ["macros"] }
thiserror = "1.0.43"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = "*"
uuid = "1.4.0"

[features]
#default = ["mensimates"]
mensimates = []

[profile.release]
strip = true
codegen-units = 1
lto = true
